### ISSUE TITLE
What is the difference between these sheets？

### ISSUE THREAD

**Issue by zhimin-z** [pkunlp-icler/PCA-EVAL#18]
Check https://docs.qq.com/sheet/DVUd4WUpGRHRqUnNV
![image](https://github.com/pkunlp-icler/PCA-EVAL/assets/8592144/5644c31a-e267-4bb9-982e-aa01e938b3d6)
Such as "工作表1" and "工作表2"...Are they also a part of the open & closed leaderboards?

**Comment by zhimin-z** [comment]
It is gone mysteriously...closed for now

**Comment by chenllliang** [comment]
Sorry for the bug. They are just temp files and
I have removed them. The leaderboard only has closed and open track.
