### ISSUE TITLE
What is the relationship between PCA-EVAL and PCA-Bench?

### ISSUE THREAD

**Issue by zhimin-z** [pkunlp-icler/PCA-EVAL#19]
I find it hard to distinguish them...Are the leaderboards tested on the former or the latter?

**Comment by chenllliang** [comment]
Hi the leaderboard is tested on PCA-Bench, which includes examples following pca-eval format.

**Comment by zhimin-z** [comment]
> hich includes examples

Can I understand PCA-EVAL is the pre-released version of PCA-Bench?

**Comment by chenllliang** [comment]
Yes, PCA-Bench completely replaces PCA-Eval

**Comment by zhimin-z** [comment]
> Yes, PCA-Bench completely replaces PCA-Eval

Understood, thanks!
